### ISSUE TITLE
Next CRAN release

### ISSUE THREAD

**Issue by mschubert** [ropensci/rzmq#36]
I'm looking to release my package [`clustermq`](https://github.com/mschubert/clustermq) (using HPC schedulers with `rzmq`) on CRAN.

However, this requires `XREQ`/`XREP` sockets (https://github.com/ropensci/rzmq/pull/32) and the updated poll timeout (https://github.com/ropensci/rzmq/pull/34). Both have been merged here.

Is there a plan when to push these changes to CRAN, so my package can make use of them without needing a Github dependency?

**Comment by jeroen** [comment]
I'll try to push out a new release today.

**Comment by jeroen** [comment]
OK this is on CRAN now.

**Comment by mschubert** [comment]
Thank you! :+1:
