### ISSUE TITLE
Question about passing messages between remote machines

### ISSUE THREAD

**Issue by wlandau** [ropensci/rzmq#43]
On an SGE cluster, I sent a message from a remote compute node:

```r
library(rzmq)
context = init.context()
socket = init.socket(context,"ZMQ_REQ")
connect.socket(socket,"tcp://localhost:5555")
send.socket(socket, data = 123)
```

and tried to receive it from the login node:

```r
library(rzmq)
context = init.context()
socket = init.socket(context,"ZMQ_REP")
bind.socket(socket,"tcp://*:5555")
receive.socket(socket)
```

Unsurprisingly, `receive.socket()` hung indefinitely (and also hung when I switched the roles of the two nodes) but returned `123` when I ran both code chunks in parallel processes on the same node. How do I come up with the socket addresses that will make the nodes talk to each other? I am having trouble finding beginner-friendly guidance in the ZeroMQ guide and references on TCP/IP.

**Comment by armstrtw** [comment]
well, you need to reply to it before it will let you send again.

once you send on a REQ socket, the internal state switches, and you can't send again on it until it receives.

why don't you try a couple of the c / c++ examples from their site.  once you get the hang of it, they are easy to switch over to R.

Also, you can find my old presentation here:
http://past.rinfinance.com/agenda/2012/workshop/WhitArmstrong.pdf

**Comment by wlandau** [comment]
Thanks Whit, sorry it has taken me a long time to respond. [`clustermq`](https://github.com/mschubert/clustermq) is helping me start to learn.

**Comment by armstrtw** [comment]
No worries.

I didn't even know about clustermq. It looks great.  I had a similar project which I never really made robust enough for prod work.
https://github.com/armstrtw/deathstar

good luck.
