### ISSUE TITLE
Fehler in rzmq::send.socket(socket = private$socket, data = list(...   lange Vektoren noch nicht unterstützt: 

### ISSUE THREAD

**Issue by pat-s** [ropensci/rzmq#51]
Sorry, I don't have the error message in English. This happens when trying to create a large object (> ~ 1 GB). I do not have a reprex, just want to let you know. Once I have more insights I'll post it here.

**Comment by mschubert** [comment]
This should already be solved in https://github.com/ropensci/rzmq/pull/47.

Try installing from git, and maybe @jeroen can push `0.9.5` to CRAN?

**Comment by jeroen** [comment]
OK I have submitted to cran.

**Comment by jeroen** [comment]
This is on cran now.
